### ISSUE TITLE
Syntax highlighting doesn't work with vim-lua

### ISSUE THREAD

**Issue by davisdude** [davisdude/vim-love-docs#14]
See https://love2d.org/forums/viewtopic.php?f=4&t=83233#p211108

**Comment by flamendless** [comment]
Hey

**Comment by davisdude** [comment]
Hey. Try moving the files "lua.vim" and "love.vim" from `.vim/syntax` to `.vim/after/syntax` and let me know if that works.

**Comment by flamendless** [comment]
Doesnt work either. Even the syntax off then on. 

Is it a problem also in your machine?

**Comment by davisdude** [comment]
No, I've never had any issues with it. It's weird that you are... especially because everything else seems to be working normally.

**Comment by davisdude** [comment]
Just to clarify, when you **type** the commands, it's fine, but when you load an old file, they aren't recognized?

*edit: Also try running `filetype plugin on` to see if that helps any

**Comment by flamendless** [comment]
Yes. When I type the commands such as love.graphics.draw(), it works. But the same line in a existing file is not. 

The filtype plugin on is not doing anything

**Comment by flamendless** [comment]
Okay, i found out something. If the line is NOT inside a function scope, it works.

**Comment by flamendless** [comment]
Here is the screenshot 
![main lua -projects-platformer - vim_260](https://cloud.githubusercontent.com/assets/17418737/24361178/ce0d0bc8-133b-11e7-893a-cf7e195c8e69.png)

**Comment by davisdude** [comment]
What plugins are you using?

**Comment by flamendless** [comment]
Here is my vimrc plugins (Aside from the vim-love-docs)

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'L9'
Plugin 'scrooloose/nerdtree'
Plugin 'luochen1990/rainbow'
Plugin 'morhetz/gruvbox'
Plugin 'vim-airline/vim-airline'
Plugin 'godlygeek/tabular'
Plugin 'tbastos/vim-lua'
Plugin 'ervandew/supertab'

**Comment by davisdude** [comment]
I think the issue might be with Vim-Lua. Can you try disabling that and let me know if it works?

**Comment by flamendless** [comment]
hey, it works! haha thanks dude.

**Comment by davisdude** [comment]
Hey, can you try building from [patch1](https://github.com/davisdude/vim-love-docs/tree/patch1) and also using vim-lua to see if it works on your end?

([Commit](https://github.com/davisdude/vim-love-docs/commit/a1ec1adedc2802566ab8e493d524efeb046f5758))

**Comment by flamendless** [comment]
Awesome dude, it works

**Comment by davisdude** [comment]
Great, thanks
