### ISSUE TITLE
Pushd and Popd errors

### ISSUE THREAD

**Issue by flamendless** [davisdude/vim-love-docs#15]
In Linux (Kubuntu 17.10 in my case), needs #!/bin/bash on top of gen.sh files in order for pushd and popd to work.

I'll update the code and PR

**Comment by davisdude** [comment]
The issue is that `pushd` and `popd` are bash builtins and not available in plain `sh`. 

Thanks for the pull requests, but since the original lines are no longer needed I went ahead and did them myself.
