### ISSUE TITLE
`lua: main.lua:42: table index is nil` while generating docs

### ISSUE THREAD

**Issue by serpent7776** [davisdude/vim-love-docs#23]
```sh
> ./gen.sh
Cloning into 'love-api'...
remote: Enumerating objects: 5121, done.
remote: Counting objects: 100% (331/331), done.
remote: Compressing objects: 100% (185/185), done.
remote: Total 5121 (delta 191), reused 250 (delta 140), pack-reused 4790
Receiving objects: 100% (5121/5121), 5.60 MiB | 3.16 MiB/s, done.
Resolving deltas: 100% (3212/3212), done.
lua: main.lua:42: table index is nil
stack traceback:
	main.lua:42: in local 'getLoveTypes'
	main.lua:603: in main chunk
	[C]: in ?
```
It looks like `t.name` is not always set to a value.
https://github.com/davisdude/vim-love-docs/blob/227e35bb50b54de25c12d05e6509774bc7bd8c83/src/doc/main.lua#L42

**Comment by davisdude** [comment]
I would consider this an issue with love-api breaking its form (returning a non-table object in its enums table), so I won't fix this for now, unless love-api decides to ignore this.

This is an issue with Lua 5.4 and how it's added functionality to `require` (see [here](https://github.com/love2d-community/love-api/issues/121) for more). Recommended to use Lua 5.3 for now (change `env.txt` to point to your Lua 5.3 interpreter) if you can.

**Comment by serpent7776** [comment]
Thanks, I tried with lua 5.2 and it does work correctly there.

**Comment by davisdude** [comment]
Fixed in https://github.com/love2d-community/love-api/commit/94f10cda74050333d6c7a0dda35fdb38d3d7daf4
