### ISSUE TITLE
Undefined variable g:lovedocs_colors

### ISSUE THREAD

**Issue by Cathedral-dark** [davisdude/vim-love-docs#24]
While launching vim on Ubuntu Linux, I get the following error:
Error detected while processing (...)/lua.vim:
line 13: 
E121: Undefined variable: g:lovedocs_colors
line 14: 
E121: Undefined variable: g:lovedocs_colors
line 15: 
E121: Undefined variable: g:lovedocs_colors
line 16: 
E121: Undefined variable: g:lovedocs_colors

Subsequently no commands are highlighted and the help file doesn't load.
If I comment those lines, the auto complete doesn't work, but the help file works fine.
Vim 8.1

**Comment by davisdude** [comment]
What is the output from when you ran the command to [generate the highlighting file](../README.md#building-the-plugin)? How are you installing the plugin? I tested with Vim 8.1 and Vim 9 and it works.

**Comment by Cathedral-dark** [comment]
I installed the pre built

**Comment by davisdude** [comment]
Ah, well this was silly. The version uploaded on vim.org was missing the `plugin/love.vim` file, which is what sets the default color if it's not defined. I've uploaded a new version that includes the file now.
